### ISSUE TITLE
Google Calendar

### ISSUE THREAD

**Issue by versionDefect** [13Bytes/eInkCalendar#3]
Hey there,

I didn't want to make this an issue but the contact me button just did not want to work for me lol. 

I have a few programs that auto-import into my Google Calendar, Is there any way that I could add my GCal to this program?

I was unable to find a webcal link for my GCal. 

Is there anyway in hell I could use Google Calendar for this?

Thanks!

**Comment by 13Bytes** [comment]
Hi,
sorry for the late reply.

Yes, I tried it and it works.
You just need to to copy from googles calendar-setting the "Private address in iCal-Format".
(In my case e.g.: https://calendar.google.com/calendar/ical/0l1dshdt8oc06ccnk2jclal5mk%40group.calendar.google.com/private-c1fef27512860198bf759cdf7d838178/basic.ics)
into the config.py and set the `WEBDAV_IS_APPLE` to `False`
