### ISSUE TITLE
RuntimeError regarding GPIO.setmode

### ISSUE THREAD

**Issue by dellis67** [13Bytes/eInkCalendar#4]
I am having trouble running "run-calendar.sh" as it gives the following error:

RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)

Please forgive me ahead of time if this is a stupid question.

Sincerely, 
David.

**Comment by 13Bytes** [comment]
Hi,
Could you provide a few more details:
- What's the type of raspi you are using?
- Did you enable the SPI interface (see Readme)?
- Could you provide the full stack trace?

Sincerely,
Louis

**Comment by dellis67** [comment]
I am using a Raspberry Pi Zero and I do have SPI enabled.

I am trying to figure out how to perform a full stack trace.

**Comment by dellis67** [comment]
<details>
  <summary>View System Log</summary>

Linux raspical 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed May 17 14:00:46 2023 from 192.168.4.151
dellis@raspical:~ $ dmesg
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 6.1.21+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1642 Mon Apr  3 17:19:14 BST 2023
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi Zero W Rev 1.1
[    0.000000] random: crng init done
[    0.000000] Memory policy: Data cache writeback
[    0.000000] Reserved memory: created CMA memory pool at 0x0bc00000, size 256 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x0000000000000000-0x000000001bffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000001bffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x000000001bffffff]
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 113680
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_headphones=0 snd_bcm2835.enable_hdmi=1 snd_bcm2835.enable_hdmi=0 video=Composite-1:720x480@60i smsc95xx.macaddr=B8:27:EB:5E:69:0C vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  console=ttyS0,115200 console=tty1 root=PARTUUID=29cb0b19-02 rootfstype=ext4 fsck.repair=yes rootwait
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 177016K/458752K available (8985K kernel code, 1450K rwdata, 2772K rodata, 432K init, 589K bss, 19592K reserved, 262144K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] ftrace: allocating 33370 entries in 98 pages
[    0.000000] ftrace: allocated 98 pages with 3 groups
[    0.000000] trace event string verifier disabled
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000008] sched_clock: 32 bits at 1000kHz, resolution 1000ns, wraps every 2147483647500ns
[    0.000082] clocksource: timer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275 ns
[    0.000179] bcm2835: system timer (irq = 27)
[    0.001070] Console: colour dummy device 80x30
[    0.001647] printk: console [tty1] enabled
[    0.001737] Calibrating delay loop... 697.95 BogoMIPS (lpj=3489792)
[    0.060331] pid_max: default: 32768 minimum: 301
[    0.060571] LSM: Security Framework initializing
[    0.060913] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.060997] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.062768] cgroup: Disabling memory control group subsystem
[    0.063247] CPU: Testing write buffer coherency: ok
[    0.065102] cblist_init_generic: Setting adjustable number of callback queues.
[    0.065190] cblist_init_generic: Setting shift to 0 and lim to 1.
[    0.065469] cblist_init_generic: Setting shift to 0 and lim to 1.
[    0.065826] Setting up static identity map for 0x8220 - 0x8258
[    0.067300] devtmpfs: initialized
[    0.080826] VFP support v0.3: implementor 41 architecture 1 part 20 variant b rev 5
[    0.081288] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.081386] futex hash table entries: 256 (order: -1, 3072 bytes, linear)
[    0.123045] pinctrl core: initialized pinctrl subsystem
[    0.125290] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.128549] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.135691] audit: initializing netlink subsys (disabled)
[    0.137439] thermal_sys: Registered thermal governor 'step_wise'
[    0.138322] hw-breakpoint: found 6 breakpoint and 1 watchpoint registers.
[    0.138426] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.138707] Serial: AMBA PL011 UART driver
[    0.140774] audit: type=2000 audit(0.130:1): state=initialized audit_enabled=0 res=1
[    0.147460] bcm2835-mbox 2000b880.mailbox: mailbox enabled
[    0.170886] raspberrypi-firmware soc:firmware: Attached to firmware from 2023-03-17T10:52:42, variant start
[    0.180916] raspberrypi-firmware soc:firmware: Firmware hash is 82f3750a65fadae9a38077e3c2e217ad158c8d54
[    0.234923] kprobes: kprobe jump-optimization is enabled. All kprobes are optimized if possible.
[    2.426788] bcm2835-dma 20007000.dma: DMA legacy API manager, dmachans=0x1
[    2.429803] SCSI subsystem initialized
[    2.430351] usbcore: registered new interface driver usbfs
[    2.430514] usbcore: registered new interface driver hub
[    2.430656] usbcore: registered new device driver usb
[    2.431080] usb_phy_generic phy: supply vcc not found, using dummy regulator
[    2.431468] usb_phy_generic phy: dummy supplies not allowed for exclusive requests
[    2.432045] pps_core: LinuxPPS API ver. 1 registered
[    2.432106] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    2.432194] PTP clock support registered
[    2.435364] clocksource: Switched to clocksource timer
[    2.567023] VFS: Disk quotas dquot_6.6.0
[    2.567230] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    2.567530] FS-Cache: Loaded
[    2.568008] CacheFiles: Loaded
[    2.589409] NET: Registered PF_INET protocol family
[    2.589844] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    2.592528] tcp_listen_portaddr_hash hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    2.592665] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    2.592752] TCP established hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    2.592879] TCP bind hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    2.593029] TCP: Hash tables configured (established 4096 bind 4096)
[    2.593216] UDP hash table entries: 256 (order: 0, 4096 bytes, linear)
[    2.593299] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes, linear)
[    2.593748] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    2.594877] RPC: Registered named UNIX socket transport module.
[    2.594964] RPC: Registered udp transport module.
[    2.595000] RPC: Registered tcp transport module.
[    2.595032] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    2.596298] armv6-pmu arm-pmu: hw perfevents: no irqs for PMU, sampling events not supported
[    2.596432] hw perfevents: enabled with armv6_1176 PMU driver, 3 counters available
[    2.600734] Initialise system trusted keyrings
[    2.601916] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    2.617062] zbud: loaded
[    2.621863] NFS: Registering the id_resolver key type
[    2.621996] Key type id_resolver registered
[    2.622040] Key type id_legacy registered
[    2.622299] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    2.622358] nfs4flexfilelayout_init: NFSv4 Flexfile Layout Driver Registering...
[    2.624808] Key type asymmetric registered
[    2.624901] Asymmetric key parser 'x509' registered
[    2.625290] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 247)
[    2.625449] io scheduler mq-deadline registered
[    2.625500] io scheduler kyber registered
[    2.630598] simple-framebuffer 1eaa9000.framebuffer: framebuffer at 0x1eaa9000, 0x151800 bytes
[    2.630711] simple-framebuffer 1eaa9000.framebuffer: format=a8r8g8b8, mode=720x480x32, linelength=2880
[    2.637275] Console: switching to colour frame buffer device 90x30
[    2.645270] simple-framebuffer 1eaa9000.framebuffer: fb0: simplefb registered!
[    2.657155] bcm2835-rng 20104000.rng: hwrng registered
[    2.661205] vc-mem: phys_addr:0x00000000 mem_base=0x1ec00000 mem_size:0x20000000(512 MiB)
[    2.669856] gpiomem-bcm2835 20200000.gpiomem: Initialised: Registers at 0x20200000
[    2.696927] brd: module loaded
[    2.713230] loop: module loaded
[    2.718000] Loading iSCSI transport class v2.0-870.
[    2.723883] usbcore: registered new interface driver smsc95xx
[    2.727469] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    3.459250] Core Release: 2.80a
[    3.462735] Setting default values for core params
[    3.466188] Finished setting default values for core params
[    3.669821] Using Buffer DMA mode
[    3.673190] Periodic Transfer Interrupt Enhancement - disabled
[    3.676604] Multiprocessor Interrupt Enhancement - disabled
[    3.679949] OTG VER PARAM: 0, OTG VER FLAG: 0
[    3.683254] Dedicated Tx FIFOs mode

[    3.687587] WARN::dwc_otg_hcd_init:1074: FIQ DMA bounce buffers: virt = cbd04000 dma = 0x8bd04000 len=9024
[    3.697354] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    3.712400] dwc_otg: Microframe scheduler enabled

[    3.712619] WARN::hcd_init_fiq:457: FIQ on core 0

[    3.718283] WARN::hcd_init_fiq:458: FIQ ASM at c065d3d8 length 36

[    3.723642] WARN::hcd_init_fiq:497: MPHI regs_base at dc810000
[    3.729171] dwc_otg 20980000.usb: DWC OTG Controller
[    3.732044] dwc_otg 20980000.usb: new USB bus registered, assigned bus number 1
[    3.734968] dwc_otg 20980000.usb: irq 56, io mem 0x00000000
[    3.737871] Init: Port Power? op_state=1
[    3.740626] Init: Power Port (0)
[    3.743680] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.01
[    3.749329] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    3.752305] usb usb1: Product: DWC OTG Controller
[    3.755225] usb usb1: Manufacturer: Linux 6.1.21+ dwc_otg_hcd
[    3.758205] usb usb1: SerialNumber: 20980000.usb
[    3.762471] hub 1-0:1.0: USB hub found
[    3.765610] hub 1-0:1.0: 1 port detected
[    3.769596] dwc_otg: FIQ enabled
[    3.769629] dwc_otg: NAK holdoff enabled
[    3.769641] dwc_otg: FIQ split-transaction FSM enabled
[    3.769669] Module dwc_common_port init
[    3.770251] usbcore: registered new interface driver usb-storage
[    3.773656] mousedev: PS/2 mouse device common for all mice
[    3.780098] sdhci: Secure Digital Host Controller Interface driver
[    3.783124] sdhci: Copyright(c) Pierre Ossman
[    3.786860] sdhci-pltfm: SDHCI platform and OF driver helper
[    3.791387] ledtrig-cpu: registered to indicate activity on CPUs
[    3.794933] hid: raw HID events driver (C) Jiri Kosina
[    3.798502] usbcore: registered new interface driver usbhid
[    3.801551] usbhid: USB HID core driver
[    3.804762] bcm2835_vchiq 2000b840.mailbox: there is not valid maps for state default
[    3.813835] Initializing XFRM netlink socket
[    3.817727] NET: Registered PF_PACKET protocol family
[    3.821437] Key type dns_resolver registered
[    3.825955] registered taskstats version 1
[    3.829114] Loading compiled-in X.509 certificates
[    3.852450] uart-pl011 20201000.serial: cts_event_workaround enabled
[    3.855968] 20201000.serial: ttyAMA0 at MMIO 0x20201000 (irq = 81, base_baud = 0) is a PL011 rev2
[    3.865881] bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer
[    3.869656] bcm2835-power bcm2835-power: Broadcom BCM2835 power domains driver
[    3.875177] mmc-bcm2835 20300000.mmcnr: mmc_debug:0 mmc_debug2:0
[    3.878487] mmc-bcm2835 20300000.mmcnr: DMA channel allocated
[    3.911041] sdhost: log_buf @ 00276dfe (8bd03000)
[    3.963534] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    3.970799] of_cfs_init
[    3.974743] of_cfs_init: OK
[    3.982956] Waiting for root device PARTUUID=29cb0b19-02...
[    4.041246] mmc0: host does not support reading read-only switch, assuming write-enable
[    4.049057] mmc0: new high speed SDXC card at address aaaa
[    4.054071] mmcblk0: mmc0:aaaa SN64G 59.5 GiB
[    4.062248]  mmcblk0: p1 p2
[    4.067107] mmcblk0: mmc0:aaaa SN64G 59.5 GiB (quirks 0x00004000)
[    4.093247] mmc1: new high speed SDIO card at address 0001
[    4.122666] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Quota mode: none.
[    4.129083] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    4.141306] devtmpfs: mounted
[    4.149833] Freeing unused kernel image (initmem) memory: 432K
[    4.153228] Kernel memory protection not selected by kernel config.
[    4.156638] Run /sbin/init as init process
[    4.159886]   with arguments:
[    4.159900]     /sbin/init
[    4.159913]   with environment:
[    4.159921]     HOME=/
[    4.159931]     TERM=linux
[    4.779557] systemd[1]: System time before build time, advancing clock.
[    5.126361] NET: Registered PF_INET6 protocol family
[    5.132388] Segment Routing with IPv6
[    5.135945] In-situ OAM (IOAM) with IPv6
[    5.248977] systemd[1]: systemd 247.3-7+rpi1+deb11u1 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified)
[    5.260514] systemd[1]: Detected architecture arm.
[    5.287582] systemd[1]: Set hostname to <raspical>.
[    8.212170] systemd[1]: Queued start job for default target Multi-User System.
[    8.228379] systemd[1]: Created slice system-getty.slice.
[    8.239901] systemd[1]: Created slice system-modprobe.slice.
[    8.250989] systemd[1]: Created slice system-systemd\x2dfsck.slice.
[    8.261383] systemd[1]: Created slice User and Session Slice.
[    8.270295] systemd[1]: Started Dispatch Password Requests to Console Directory Watch.
[    8.279408] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[    8.290180] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    8.303064] systemd[1]: Reached target Local Encrypted Volumes.
[    8.312590] systemd[1]: Reached target Paths.
[    8.321579] systemd[1]: Reached target Slices.
[    8.330292] systemd[1]: Reached target Swap.
[    8.341009] systemd[1]: Listening on Syslog Socket.
[    8.351090] systemd[1]: Listening on fsck to fsckd communication Socket.
[    8.360525] systemd[1]: Listening on initctl Compatibility Named Pipe.
[    8.371787] systemd[1]: Listening on Journal Audit Socket.
[    8.382128] systemd[1]: Listening on Journal Socket (/dev/log).
[    8.392788] systemd[1]: Listening on Journal Socket.
[    8.406852] systemd[1]: Listening on udev Control Socket.
[    8.417164] systemd[1]: Listening on udev Kernel Socket.
[    8.427445] systemd[1]: Condition check resulted in Huge Pages File System being skipped.
[    8.444330] systemd[1]: Mounting POSIX Message Queue File System...
[    8.477152] systemd[1]: Mounting RPC Pipe File System...
[    8.536534] systemd[1]: Mounting Kernel Debug File System...
[    8.606106] systemd[1]: Mounting Kernel Trace File System...
[    8.614796] systemd[1]: Condition check resulted in Kernel Module supporting RPCSEC_GSS being skipped.
[    8.658097] systemd[1]: Starting Restore / save the current clock...
[    8.700334] systemd[1]: Starting Set the console keyboard layout...
[    8.759378] systemd[1]: Starting Create list of static device nodes for the current kernel...
[    8.868785] systemd[1]: Starting Load Kernel Module configfs...
[    8.947013] systemd[1]: Starting Load Kernel Module drm...
[    9.029499] systemd[1]: Starting Load Kernel Module fuse...
[    9.088430] systemd[1]: Condition check resulted in Set Up Additional Binary Formats being skipped.
[    9.175452] systemd[1]: Starting File System Check on Root Device...
[    9.317535] systemd[1]: Starting Journal Service...
[    9.457202] systemd[1]: Starting Load Kernel Modules...
[    9.532262] fuse: init (API version 7.37)
[    9.607314] systemd[1]: Starting Coldplug All udev Devices...
[    9.842296] systemd[1]: Mounted POSIX Message Queue File System.
[    9.921437] systemd[1]: Mounted RPC Pipe File System.
[    9.980012] systemd[1]: Mounted Kernel Debug File System.
[   10.089158] systemd[1]: Mounted Kernel Trace File System.
[   10.179714] systemd[1]: Finished Restore / save the current clock.
[   10.275776] systemd[1]: Finished Create list of static device nodes for the current kernel.
[   10.351021] systemd[1]: modprobe@configfs.service: Succeeded.
[   10.427664] systemd[1]: Finished Load Kernel Module configfs.
[   10.461556] systemd[1]: modprobe@drm.service: Succeeded.
[   10.535732] systemd[1]: Finished Load Kernel Module drm.
[   10.587629] systemd[1]: modprobe@fuse.service: Succeeded.
[   10.615798] systemd[1]: Finished Load Kernel Module fuse.
[   10.685728] systemd[1]: Finished Load Kernel Modules.
[   10.826000] systemd[1]: Mounting FUSE Control File System...
[   11.025936] systemd[1]: Mounting Kernel Configuration File System...
[   11.147082] systemd[1]: Started File System Check Daemon to report status.
[   11.297459] systemd[1]: Starting Apply Kernel Variables...
[   11.445810] systemd[1]: Finished File System Check on Root Device.
[   11.509789] systemd[1]: Mounted FUSE Control File System.
[   11.579288] systemd[1]: Mounted Kernel Configuration File System.
[   11.687345] systemd[1]: Starting Remount Root and Kernel File Systems...
[   11.855162] systemd[1]: Started Journal Service.
[   12.716599] EXT4-fs (mmcblk0p2): re-mounted. Quota mode: none.
[   13.297312] systemd-journald[106]: Received client request to flush runtime journal.
[   17.941141] vc_sm_cma: module is from the staging directory, the quality is unknown, you have been warned.
[   17.943901] bcm2835_vc_sm_cma_probe: Videocore shared memory driver
[   17.943953] [vc_sm_connected_init]: start
[   18.022636] [vc_sm_connected_init]: installed successfully
[   18.075946] mc: Linux media interface: v0.10
[   19.252383] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[   19.396185] videodev: Linux video capture interface: v2.00
[   20.221558] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[   20.265926] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[   20.273544] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[   20.534950] bcm2835_isp: module is from the staging directory, the quality is unknown, you have been warned.
[   20.769686] bcm2835_v4l2: module is from the staging directory, the quality is unknown, you have been warned.
[   20.837395] bcm2835-isp bcm2835-isp: Device node output[0] registered as /dev/video13
[   20.853472] bcm2835-isp bcm2835-isp: Device node capture[0] registered as /dev/video14
[   20.860023] bcm2835-isp bcm2835-isp: Device node capture[1] registered as /dev/video15
[   20.860786] bcm2835-isp bcm2835-isp: Device node stats[2] registered as /dev/video16
[   20.860856] bcm2835-isp bcm2835-isp: Register output node 0 with media controller
[   20.860899] bcm2835-isp bcm2835-isp: Register capture node 1 with media controller
[   20.860932] bcm2835-isp bcm2835-isp: Register capture node 2 with media controller
[   20.860962] bcm2835-isp bcm2835-isp: Register capture node 3 with media controller
[   20.911586] bcm2835-isp bcm2835-isp: Device node output[0] registered as /dev/video20
[   20.912698] bcm2835-isp bcm2835-isp: Device node capture[0] registered as /dev/video21
[   20.914163] bcm2835-isp bcm2835-isp: Device node capture[1] registered as /dev/video22
[   20.928312] bcm2835-isp bcm2835-isp: Device node stats[2] registered as /dev/video23
[   20.928394] bcm2835-isp bcm2835-isp: Register output node 0 with media controller
[   20.928436] bcm2835-isp bcm2835-isp: Register capture node 1 with media controller
[   20.928471] bcm2835-isp bcm2835-isp: Register capture node 2 with media controller
[   20.928500] bcm2835-isp bcm2835-isp: Register capture node 3 with media controller
[   20.931202] bcm2835-isp bcm2835-isp: Loaded V4L2 bcm2835-isp
[   21.133871] bcm2835_codec: module is from the staging directory, the quality is unknown, you have been warned.
[   21.457425] bcm2835-codec bcm2835-codec: Device registered as /dev/video10
[   21.457520] bcm2835-codec bcm2835-codec: Loaded V4L2 decode
[   21.476732] bcm2835-codec bcm2835-codec: Device registered as /dev/video11
[   21.476839] bcm2835-codec bcm2835-codec: Loaded V4L2 encode
[   21.517884] bcm2835-codec bcm2835-codec: Device registered as /dev/video12
[   21.518004] bcm2835-codec bcm2835-codec: Loaded V4L2 isp
[   21.548407] bcm2835-codec bcm2835-codec: Device registered as /dev/video18
[   21.548502] bcm2835-codec bcm2835-codec: Loaded V4L2 image_fx
[   21.588876] bcm2835-codec bcm2835-codec: Device registered as /dev/video31
[   21.588971] bcm2835-codec bcm2835-codec: Loaded V4L2 encode_image
[   27.743388] uart-pl011 20201000.serial: no DMA platform data
[   27.919902] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SSFS
[   30.415202] 8021q: 802.1Q VLAN Support v1.8
[   31.164361] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[   31.518420] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   31.535626] cfg80211: loaded regulatory.db is malformed or signature is missing/invalid
[   32.815808] Console: switching to colour dummy device 80x30
[   32.827094] vc4-drm soc:gpu: bound 20400000.hvs (ops vc4_hvs_ops [vc4])
[   32.871660] Registered IR keymap rc-cec
[   32.871967] rc rc0: vc4-hdmi as /devices/platform/soc/20902000.hdmi/rc/rc0
[   32.872261] input: vc4-hdmi as /devices/platform/soc/20902000.hdmi/rc/rc0/input0
[   32.921619] vc4-drm soc:gpu: bound 20902000.hdmi (ops vc4_hdmi_ops [vc4])
[   32.922541] vc4-drm soc:gpu: bound 20004000.txp (ops vc4_txp_ops [vc4])
[   32.923305] vc4-drm soc:gpu: bound 20206000.pixelvalve (ops vc4_crtc_ops [vc4])
[   32.924061] vc4-drm soc:gpu: bound 20207000.pixelvalve (ops vc4_crtc_ops [vc4])
[   32.924784] vc4-drm soc:gpu: bound 20807000.pixelvalve (ops vc4_crtc_ops [vc4])
[   32.977811] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[   33.035050] vc4-drm soc:gpu: bound 20c00000.v3d (ops vc4_v3d_ops [vc4])
[   33.145962] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[   33.147623] usbcore: registered new interface driver brcmfmac
[   33.170029] [drm] Initialized vc4 0.0.0 20140616 for soc:gpu on minor 0
[   33.186208] vc4-drm soc:gpu: [drm] Cannot find any crtc or sizes
[   33.423281] Bluetooth: Core ver 2.22
[   33.423451] NET: Registered PF_BLUETOOTH protocol family
[   33.423467] Bluetooth: HCI device and connection manager initialized
[   33.423500] Bluetooth: HCI socket layer initialized
[   33.423519] Bluetooth: L2CAP socket layer initialized
[   33.423556] Bluetooth: SCO socket layer initialized
[   33.424693] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Jul 19 2021 03:24:18 version 7.45.98 (TOB) (56df937 CY) FWID 01-8e14b897
[   33.573817] Bluetooth: HCI UART driver ver 2.3
[   33.573859] Bluetooth: HCI UART protocol H4 registered
[   33.573988] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   33.574229] Bluetooth: HCI UART protocol Broadcom registered
[   36.541143] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   36.541183] Bluetooth: BNEP filters: protocol multicast
[   36.541214] Bluetooth: BNEP socket layer initialized
[   36.604172] Bluetooth: MGMT ver 1.22
[   36.709715] NET: Registered PF_ALG protocol family
[   37.055246] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
[   43.973117] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   45.458075] ICMPv6: process `dhcpcd' is using deprecated sysctl (syscall) net.ipv6.neigh.wlan0.retrans_time - use net.ipv6.neigh.wlan0.retrans_time_ms instead

</details>

**Comment by 13Bytes** [comment]
Sorry for being unclear.
I ment the stack trace of the programm(error). So just the full error message.
(In particular to get the information in which line the programm fails.)

You should be abel to run `./displayRun.py` directly. (I excpect the problem in there.)

**Comment by dellis67** [comment]
Sorry for the delay; I had to leave for 10 days for doctor's visits, etc, on the mainland. Anyway, I've got the trace of the error:

dellis@raspical:/eInkCalendar $ sudo python3 ./displayRun.py
INFO:app:2023-06-01 17:27:24.615902
WARNING:app:unsupported locale setting
INFO:app:Trying to module_exit()
Traceback (most recent call last):
  File "/eInkCalendar/./displayRun.py", line 63, in main
    render_content(draw_blk, image_blk, draw_red,
  File "/eInkCalendar/./displayRun.py", line 77, in render_content
    locale.setlocale(locale.LC_ALL, LOCALE)
  File "/usr/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/eInkCalendar/./displayRun.py", line 212, in <module>
    main()
  File "/eInkCalendar/./displayRun.py", line 72, in main
    eInk.epdconfig.module_exit()
  File "/eInkCalendar/lib/epdconfig.py", line 86, in module_exit
    self.GPIO.output(self.RST_PIN, 0)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)

Running the displayRun.py give this:

dellis@raspical:/eInkCalendar $ sudo ./displayRun.py
sudo: ./displayRun.py: command not found
dellis@raspical:/eInkCalendar $ sudo python3 ./displayRun.py
INFO:app:2023-06-01 17:27:24.615902
WARNING:app:unsupported locale setting
INFO:app:Trying to module_exit()
Traceback (most recent call last):
  File "/eInkCalendar/./displayRun.py", line 63, in main
    render_content(draw_blk, image_blk, draw_red,
  File "/eInkCalendar/./displayRun.py", line 77, in render_content
    locale.setlocale(locale.LC_ALL, LOCALE)
  File "/usr/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/eInkCalendar/./displayRun.py", line 212, in <module>
    main()
  File "/eInkCalendar/./displayRun.py", line 72, in main
    eInk.epdconfig.module_exit()
  File "/eInkCalendar/lib/epdconfig.py", line 86, in module_exit
    self.GPIO.output(self.RST_PIN, 0)
RuntimeError: Please set pin numbering mode using GPIO.setmode(GPIO.BOARD) or GPIO.setmode(GPIO.BCM)
dellis@raspical:/eInkCalendar $

**Comment by 13Bytes** [comment]
Thanks, this helps.
It seems like your locale-setting is off.
Could you check the `LOCALE = ...` line in `settings.py`?
(Feel free to post it here)

**Comment by dellis67** [comment]
I have   
LOCALE = "en_US"

**Comment by dellis67** [comment]
I changed it to "en_US.UTF-8" after setting that in the Locales settings, and it works. Thank you so much for you help!
